#!/usr/bin/env python3
import os
import argparse
from pathlib import Path
from shutil import copy

import pyfplo.fedit as fedit

parser = argparse.ArgumentParser(
    description='Create new FPLO run based on current working directory run.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
parser.add_argument('dir', metavar='DIR', type=lambda x: Path(x).absolute(), help='new FPLO run directory', nargs='+')
args = parser.parse_args()

src = Path.cwd()
copy_list = list(src.glob('./=.*'))  # absolute source file paths

prevent_repeated_spinsplit = True

for d in args.dir:  # absolute destination paths
    d.mkdir()
    for fname in copy_list:
        copy(fname, d)

    if src/"=.dens" in copy_list and prevent_repeated_spinsplit:
        os.chdir(d)
        print(f'NOTE: setting initialspinsplit=False on subdirectory {d}')
        fed = fedit.Fedit()
        fed.spin(initialspinsplit=False)
        fed.pipeFedit()
        os.chdir(src)  # poor man's context manager, only needed for rel paths
